'use strict';
const router = require('express').Router();
const { requireAuth } = require('../../middleware/auth');
const { requireRole } = require('../../middleware/rbac');
const ctrl = require('./controller');
router.get('/',       requireAuth, requireRole('ADMIN','FINANCE','SALES_MANAGER'), ctrl.list);
router.get('/:id',    requireAuth, requireRole('ADMIN','FINANCE','SALES_MANAGER'), ctrl.getOne);
router.post('/',      requireAuth, requireRole('ADMIN','FINANCE'), ctrl.create);
router.put('/:id',    requireAuth, requireRole('ADMIN','FINANCE'), ctrl.update);
router.delete('/:id', requireAuth, requireRole('ADMIN','FINANCE'), ctrl.remove);
module.exports = router;
