'use strict';

/**
 * Invoices Service
 * ================
 * Per Global Constraint 7:
 *   - One-time invoices are generated at order confirmation.
 *   - Recurring invoices are generated by the monthly cron job.
 *   - ONE_TIME and RECURRING lines NEVER merge onto the same invoice.
 *   - PDF generated via pdfkit, path stored in invoice.pdfPath.
 *   - Invoice emails go to customer.realEmail (NEVER the portal login address).
 */

const path    = require('path');
const fs      = require('fs');
const PDFDocument = require('pdfkit');
const prisma  = require('../../config/prisma');
const { logAudit }  = require('../../utils/logAudit');
const { sendMail }  = require('../../config/mailer');
const realtime      = require('../../realtime/index');
const subscriptionSvc = require('../subscriptions/service');

// Directory to store generated PDFs (created at module load if absent)
const PDF_DIR = path.join(__dirname, '../../../../invoices-pdf');
if (!fs.existsSync(PDF_DIR)) fs.mkdirSync(PDF_DIR, { recursive: true });

// ── Helpers ────────────────────────────────────────────────────────────────────

/**
 * Generate a PDF invoice file using pdfkit.
 * Returns the absolute file path where the PDF was written.
 *
 * @param {object} invoice  — full invoice record with lines
 * @param {object} customer — { companyName, realEmail }
 * @param {Array}  lines    — quotation line items
 * @returns {Promise<string>} absolute path to the PDF file
 */
async function _generatePdf(invoice, customer, lines) {
  const filename = `invoice-${invoice.id}.pdf`;
  const filepath = path.join(PDF_DIR, filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('DealFlow360', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#555')
       .text('Tax Invoice', 50, 75);

    // Invoice meta
    doc.moveTo(50, 95).lineTo(560, 95).stroke('#ddd');
    doc.fontSize(10).fillColor('#000')
       .text(`Invoice #: ${invoice.id.slice(0, 8).toUpperCase()}`, 50, 105)
       .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 50, 120)
       .text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, 50, 135)
       .text(`Status: ${invoice.status}`, 50, 150);

    // Customer
    doc.text(`Bill To: ${customer.companyName}`, 350, 105);

    // Lines table
    doc.moveTo(50, 170).lineTo(560, 170).stroke('#ddd');
    doc.font('Helvetica-Bold').fontSize(9)
       .text('Product', 50, 180)
       .text('Qty', 280, 180)
       .text('Unit Price', 330, 180)
       .text('Discount', 410, 180)
       .text('Total', 490, 180);

    doc.moveTo(50, 195).lineTo(560, 195).stroke('#ddd');

    let y = 205;
    let subtotal = 0;
    for (const l of (lines ?? [])) {
      const base  = Number(l.unitPrice) * l.quantity;
      const disc  = base * (Number(l.discountPercent) / 100);
      const total = base - disc;
      subtotal   += total;

      doc.font('Helvetica').fontSize(9)
         .text(l.product?.name ?? l.productId, 50, y, { width: 220 })
         .text(String(l.quantity), 280, y)
         .text(`$${Number(l.unitPrice).toFixed(2)}`, 330, y)
         .text(`${Number(l.discountPercent).toFixed(1)}%`, 410, y)
         .text(`$${total.toFixed(2)}`, 490, y);
      y += 18;
    }

    // Total
    doc.moveTo(50, y + 5).lineTo(560, y + 5).stroke('#ddd');
    doc.font('Helvetica-Bold').fontSize(10)
       .text('Total', 410, y + 12)
       .text(`$${Number(invoice.amount).toFixed(2)}`, 490, y + 12);

    // Footer
    doc.fontSize(8).font('Helvetica').fillColor('#999')
       .text('DealFlow360 — Payment due within 30 days.', 50, y + 40, { align: 'center', width: 510 });

    doc.end();
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}

// ── Public API ─────────────────────────────────────────────────────────────────

async function list(query, user) {
  const where = {};
  // Global Constraint 5: CUSTOMER sees only their own invoices
  if (user.role === 'CUSTOMER') {
    where.order = { quotation: { customerId: user.customerId } };
  }
  if (query?.status) where.status = query.status;
  if (query?.type)   where.type   = query.type;

  return prisma.invoice.findMany({
    where,
    include: { order: { include: { quotation: { include: { customer: { select: { id: true, companyName: true } } } } } } },
    orderBy: { createdAt: 'desc' },
  });
}

async function getOne(id, user) {
  const invoice = await prisma.invoice.findUniqueOrThrow({
    where:   { id },
    include: {
      order: {
        include: {
          quotation: {
            include: {
              customer: true,
              lines: { include: { product: { select: { id: true, name: true, unit: true } } } },
            },
          },
        },
      },
    },
  });

  // Customer scope check
  if (user.role === 'CUSTOMER') {
    if (invoice.order?.quotation?.customerId !== user.customerId) {
      const e = new Error('Access denied'); e.statusCode = 403; throw e;
    }
  }

  return invoice;
}

/**
 * Create a ONE_TIME invoice at order confirmation.
 * Called internally by the order-confirmation flow (not exposed as a public
 * REST endpoint for reps to call arbitrarily).
 *
 * @param {string} orderId
 * @param {object} [actor] — the user who confirmed the order (or null for system)
 */
async function createOneTimeInvoice(orderId, actor = null) {
  const order = await prisma.order.findUniqueOrThrow({
    where:   { id: orderId },
    include: {
      quotation: {
        include: {
          customer: true,
          lines: {
            where:   { lineType: 'ONE_TIME' },
            include: { product: { select: { id: true, name: true, unit: true } } },
          },
        },
      },
    },
  });

  const oneTimeLines = order.quotation.lines;
  if (oneTimeLines.length === 0) return null; // no one-time lines

  // Compute total (sum of line totals after discount)
  const amount = oneTimeLines.reduce((sum, l) => {
    const base = Number(l.unitPrice) * l.quantity;
    return sum + base * (1 - Number(l.discountPercent) / 100);
  }, 0);

  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 30); // net-30

  const invoice = await prisma.invoice.create({
    data: {
      orderId,
      type:   'ONE_TIME',
      amount: Math.round(amount * 100) / 100,
      status: 'UNPAID',
      dueDate,
    },
  });

  // Generate PDF
  const pdfPath = await _generatePdf(
    { ...invoice, createdAt: new Date() },
    order.quotation.customer,
    oneTimeLines
  );
  await prisma.invoice.update({ where: { id: invoice.id }, data: { pdfPath } });

  await logAudit({
    userId:     actor?.userId ?? null,
    action:     'INVOICE_CREATED_ONE_TIME',
    entityType: 'Invoice',
    entityId:   invoice.id,
    details:    { orderId, amount, linesCount: oneTimeLines.length },
  });

  return { ...invoice, pdfPath };
}

/**
 * Create RECURRING subscriptions for all RECURRING lines on a confirmed order.
 * Called after order confirmation in the same flow as createOneTimeInvoice.
 *
 * @param {string} orderId
 * @param {object} [actor]
 */
async function createRecurringSubscriptions(orderId, actor = null) {
  const order = await prisma.order.findUniqueOrThrow({
    where:   { id: orderId },
    include: {
      quotation: {
        include: {
          lines: { where: { lineType: 'RECURRING' } },
        },
      },
    },
  });

  const recurringLines = order.quotation.lines;
  if (recurringLines.length === 0) return [];

  const created = [];
  for (const line of recurringLines) {
    if (!line.subscriptionPlanId) continue;
    const sub = await subscriptionSvc.create(
      { orderId, planId: line.subscriptionPlanId, quantity: line.quantity },
      actor ?? { userId: null }
    );
    created.push(sub);
  }

  return created;
}

/**
 * Process an order confirmation: create one-time invoice + recurring subscriptions.
 * This is the single entry point called after a quotation is CONFIRMED.
 *
 * @param {string} orderId
 * @param {object} [actor]
 */
async function processOrderConfirmation(orderId, actor = null) {
  const [oneTimeInvoice, subscriptions] = await Promise.all([
    createOneTimeInvoice(orderId, actor),
    createRecurringSubscriptions(orderId, actor),
  ]);

  return { oneTimeInvoice, subscriptions };
}

module.exports = { list, getOne, createOneTimeInvoice, createRecurringSubscriptions, processOrderConfirmation };
